#!/bin/bash
# Massive Network Game Object Server
# autorestart Script

while :
do
	echo "Worldserver restarted"
	echo `date` >> crash.log &
	./worldserver | tail -n 20 >> crash.log
	echo " " >> crash.log &
	pid=`ps ax | awk '($5 ~ /worldserver/) { print $1 }'`
	wait $pid
        echo `date` ", Worldserver crashed and restarted." >> serverlog
done
